default: &default
  host: localhost
  adapter: postgres

development:
  <<: *default
  db: postgres
  user: postgres
  password: "123456"
  port: "5432"
  migration_files_path: "db/migrations"
  model_files_path: "src/models"
